import cover from '../assets/images/Cover.png';

export const MOVIE_DETAILS = [
  {
    id: 1,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 2,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 3,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 4,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 5,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 6,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 7,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 8,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 9,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
  {
    id: 10,
    cover: cover,
    releaseDate: 'USA, 2016 - Current',
    movieTitle: 'Stranger Things',
    IMDB: '86.0 / 100',
    tomato: '97%',
    genre: 'Action, Adventure, Horror',
  },
];
